spring:
  rabbitmq:
    host: 39.105.189.141
    username: guest
    password: guest
    port: 5672
  application:
    name: SearchProvider
  data:
    elasticsearch:
      cluster-name: qfjava
      cluster-nodes: 39.105.189.141:9300
server:
  port: 9601
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

